# Generated by Django 4.1.2 on 2022-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('held', models.CharField(choices=[('comming', 'comming'), ('closed', 'closed')], default='comming', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('O', 'O')], default='A+', max_length=3)),
                ('phone', models.CharField(max_length=15)),
                ('adress', models.CharField(max_length=200)),
                ('dibetis', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('heart_deases', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('last_time_donated', models.DateField(default='2021-01-01')),
            ],
        ),
    ]
